# Generated by Django 6.0.4 on 2026-04-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('operational', 'Operational'), ('salary', 'Salary'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
